#==================== 通用代价地图参数 ====================
# 机器人的几何形状，可以是'footprint'或'robot_radius'
# footprint: [[x1, y1], [x2, y2], ..., [xn, yn]] # 对于非圆形机器人
# robot_radius: 0.35 # 对于圆形机器人，单位：米
footprint: [[-0.25, -0.15], [0.25, -0.15], [0.25, 0.15], [-0.25, 0.15]]
resolution: 0.1


# 代价递减因子，越高，离障碍物越远代价越小
cost_scaling_factor: 3.0

obstacle_layer:
  enabled: true
  obstacle_range: 2.5                  # 扩展障碍检测范围
  raytrace_range: 3.0                  # 增加光线追踪距离
  track_unknown_space: true             # 跟踪未知空间
  combination_method: 1                 # 使用最大值法
  # 传感器配置
  # observation_sources定义了用于更新代价地图的传感器信息
  observation_sources: laser_scan_sensor
  # 为上面定义的每个传感器源进行详细配置
  laser_scan_sensor: {
    sensor_frame: laser_link,    # 传感器坐标系名称 (!!需要修改!!)
    data_type: LaserScan,             # 传感器数据类型
    topic: /laser_scan,                     # 传感器发布的话题 (!!需要修改!!)
    marking: true,                    # 是否用传感器数据标记障碍物
    clearing: true,                   # 是否用传感器数据清除障碍物
    observation_persistence: 0.2,  # 观测数据保留时间（秒），过时后自动清除（建议0.5~1.0）
    max_obstacle_height: 1.0,         # 障碍物的最大高度（米），高于此高度的将被忽略
    min_obstacle_height: -0.1         # 障碍物的最小高度（米），低于此高度的将被忽略
  }



static_layer:
  enabled: true
  map_topic: "map_grid"